# A.2 Extensión de ecosistemas naturales

**Objetivo del Indicador**: medir la extensión (superficie) de los ecosistemas naturales y seminaturales y reportar como proporción del territorio nacional.
**Alcance Espacial**: El reporte debe cubrir la totalidad de la jurisdicción nacional, compuesta por:
- [ ] Territorio Continental e Insular: Basado en límites administrativos.
- [ ] Territorio Marino: Basado en la Zona Económica Exclusiva (ZEE - 200 millas náuticas).

## Fuentes de datos y descripción


A. **Para Ecosistemas Terrestres y Costeros**

Catastro de los Recursos Vegetacionales Nativos de Chile (CONAF) https://sit.conaf.cl/ 
Gestión de la Heterogeneidad Temporal : Dado que el Catastro CONAF no posee un año único de actualización nacional, se debe construir un "Mosaico Nacional".

B. **Para Ecosistemas Marinos**

Capa vectorial de la Zona Económica Exclusiva (ZEE) de Chile. Consultar con Daniel por capa usada para indicador de áreas protegidas

**Capa Complementaria**

Capa de Grupos Funcionales de Ecosistemas (EFG - UICN). (Nota: Esta capa se encuentra en desarrollo).

## Metodología De Procesamiento

El procesamiento se divide en dos flujos que luego se integran.

### Flujo 1: Proccesamiento Terrestre (CONAF)

#### Paso 1.1: Filtrado de Áreas Naturales

Utilizar atributos USO y SUBUSO del Catastro CONAF.

CLASES A INCLUIR:
- [X] Bosque Nativo: (Todos los tipos).
- [X] Praderas y Matorrales: (Matorral, Estepa, Pradera natural).
- [X] Humedales: (Vegas, bofedales, pajonales).
- [X] Áreas desprovistas (Naturales): Desiertos, dunas, playas, nieves, glaciares, roqueríos.
- [X] Cuerpos de Agua: Lagos, lagunas, ríos.

CLASES A EXCLUIR (Descartar):
- [ ] Terrenos Agrícolas, Plantaciones Forestales, Áreas Urbanas/Industriales, Embalses artificiales.

In [1]:
import os
import pandas as pd
import geopandas as gpd
from sqlalchemy import create_engine, text
from dotenv import load_dotenv

load_dotenv("../local.env")
engine = create_engine("postgresql://{user}:{password}@localhost:5432/{dbname}".format(
    dbname=os.environ.get("SEVENNR_DB_NAME"),
    user=os.environ.get("SEVENNR_DB_USER"),
    password=os.environ.get("SEVENNR_DB_PASSWORD"),
))

In [2]:
%%time
with engine.connect() as conn:
    uso_subuso = pd.read_sql_table("uso_subuso", conn, schema="processed")
uso_subuso

WARNING:  database "7nr" has a collation version mismatch
DETAIL:  The database was created using collation version 2.41, but the operating system provides version 2.31.
HINT:  Rebuild all objects in this database that use the default collation and run ALTER DATABASE "7nr" REFRESH COLLATION VERSION, or build PostgreSQL with the right library version.

CPU times: user 94.5 ms, sys: 15.7 ms, total: 110 ms
Wall time: 1.99 s

,id_uso,id_subuso,uso,subuso,incluir,superf_ha
0,1,2,Ãreas Urbanas e Industriales,MinerÃ­a Industrial,False,NaN
1,2,1,Terrenos AgrÃ­colas,Terreno de Uso AgrÃ­cola,False,NaN
2,2,2,Terrenos AgrÃ­colas,RotaciÃ³n Cultivo-Pradera,False,NaN
3,3,1,Praderas y Matorrales,Praderas,True,NaN
4,3,2,Praderas y Matorrales,Matorral-Pradera,True,NaN
5,3,3,Praderas y Matorrales,Matorral,True,NaN
6,3,4,Praderas y Matorrales,Matorral Arborescente,True,NaN
7,3,5,Praderas y Matorrales,Matorral con Suculentas,True,NaN
8,3,6,Praderas y Matorrales,FormaciÃ³n de Suculentas,True,NaN
9,3,7,Praderas y Matorrales,PlantaciÃ³n de Arbustos,False,NaN
10,3,8,Praderas y Matorrales,Tundra MagallÃ¡nica,True,NaN
11,4,1,Bosques,PlantaciÃ³n,False,NaN
12,4,2,Bosques,Bosque Nativo,True,NaN
13,4,3,Bosques,Bosque Mixto,True,NaN
14,5,1,Humedales,VegetaciÃ³n HerbÃ¡cea en Orillas de RÃ­os,True,NaN
15,5,2,Humedales,Marismas HerbÃ¡ceas,True,NaN
16,5,3,Humedales,Ã‘adis,True,NaN
17,5,4,Humedales,Turbales,True,NaN
18,5,5,Humedales,Bofedales,True,NaN
19,5,6,Humedales,Vegas,True,NaN
20,5,7,Humedales,Otros Terrenos HÃºmedos,True,NaN
21,6,1,Ãreas Desprovistas de VegetaciÃ³n,Playas y Dunas,True,NaN
22,6,2,Ãreas Desprovistas de VegetaciÃ³n,Afloramientos Rocosos,True,NaN
23,6,3,Ãreas Desprovistas de VegetaciÃ³n,Terrenos sobre el LÃ­mite Altitudinal de la Ve...,True,NaN
24,6,4,Ãreas Desprovistas de VegetaciÃ³n,Corridas de Lavas y Escoriales,True,NaN
25,6,5,Ãreas Desprovistas de VegetaciÃ³n,Derrumbe sin VegetaciÃ³n,True,NaN
26,6,6,Ãreas Desprovistas de VegetaciÃ³n,Salares,True,NaN
27,6,7,Ãreas Desprovistas de VegetaciÃ³n,Otros Terrenos sin VegetaciÃ³n,True,NaN
28,6,8,Ãreas Desprovistas de VegetaciÃ³n,Cajas de RÃ­os,True,NaN
29,7,1,Nieves Eternas y Glaciares,Nieves,True,NaN
30,7,2,Nieves Eternas y Glaciares,Glaciares,True,NaN
31,7,3,Nieves Eternas y Glaciares,Campos de Hielos,True,NaN
32,8,1,Cuerpos de Agua,Mar,True,NaN
33,8,2,Cuerpos de Agua,RÃ­os,True,NaN
34,8,3,Cuerpos de Agua,"Lagos, Lagunas, Embalses, Tranques",True,NaN
35,9,1,ÃƒÂreas no Reconocidas,ÃƒÂreas de Acceso Restringido,False,NaN
36,1,1,Ãreas Urbanas e Industriales,"Ciudades, Pueblos, Zonas Industriales",False,NaN

Procesamiento de datos desde los descargables se realiza a través de un script de python. Los datos estandarizados se registran en una base de datos intermedia.

El área total se calcula sumando la columna `superf_ha` de los datos de CONAF filtrando por la columna de `incluir`:

In [3]:
%%time
with engine.connect() as conn:
    area_natural_terrestre = pd.read_sql_query("""
        SELECT incluir, sum(ct.superf_ha) AS "area"
        FROM processed.conaf_terrestre ct
        	JOIN processed.uso_subuso us
        		ON ct.id_uso = us.id_uso AND ct.id_subuso = us.id_subuso 
        GROUP BY incluir;
    """, conn)
area_natural = area_natural_terrestre.loc[1, 'area']
area_total = area_natural_terrestre["area"].sum()
area_natural_terrestre

CPU times: user 4.61 ms, sys: 4.05 ms, total: 8.66 ms
Wall time: 19.1 s

   incluir          area
0    False  8.479620e+06
1     True  6.720843e+07

In [4]:
print(f"Área natural total: {area_natural:.2f} ha")
print(f"Porcentaje con el área total: {area_natural*100/area_total:.2f}%")

Área natural total: 67208431.29 ha
Porcentaje con el área total: 88.80%

#### Paso 1.2: Intersección EFG Terrestre (esperar capa EFG)

Cruzar la capa filtrada de CONAF con la capa de Grupos Funcionales UICN para asignar etiquetas (ej. T2.2, T3.2).

Las capas de EFG terrestre y marino fueron unidas por cada grupo funcional y almacenadas en una base de datos intermedia utilizando un script de Python.

Para cada grupo funcional se elimina los polígonos no incluidos como áreas naturales utilizando un nuevo script de Python. Los resultados se almacenan en la base de datos intermedia. Los resultados se muestran consultando a dicha base de datos.

In [5]:
%%time
with engine.connect() as conn:
    efg_terrestre = pd.read_sql_query("""
        SELECT ec."group", ec.superf_ha "area_total", eci.superf_ha "area_natural", eci.superf_ha / ec.superf_ha "porcentaje"
        FROM processed.efg_continental ec
        	JOIN processed.efg_continental_included eci
        		ON ec."group" = eci."group";
    """, conn)
efg_terrestre

CPU times: user 2.79 ms, sys: 1.91 ms, total: 4.71 ms
Wall time: 182 ms

,group,area_total,area_natural,porcentaje
0,Boreal and temperate fens,1.886958e+05,1.852795e+05,0.981895
1,"Boreal, temperate and montane peat bogs",5.350073e+06,5.349428e+06,0.999879
2,Coastal saltmarshes and reedbeds,4.482446e+04,4.436791e+04,0.989815
3,Constructed lacustrine wetlands,5.334631e+02,2.471516e+02,0.463296
4,Episodic arid floodplains,3.025242e+01,8.792613e+00,0.290642
5,Episodic arid rivers,2.385599e+04,2.290089e+04,0.959964
6,Geothermal pools and wetlands,5.501596e+02,5.501596e+02,1.000000
7,Hyper-arid deserts,5.827816e+06,5.612599e+06,0.963071
8,"Ice sheets, glaciers and perennial snowfields",1.806099e+06,1.806082e+06,0.999991
9,Intermittently closed and open lakes and lagoons,1.205930e+04,1.145794e+04,0.950134
10,Large permanent freshwater lakes,1.239736e+06,1.232441e+06,0.994116
11,Large reservoirs,3.615980e+04,2.914710e+04,0.806064
12,Muddy Shorelines,3.519240e+05,3.377234e+05,0.959649
13,Oceanic cool temperate rainforests,2.227194e+07,1.805185e+07,0.810520
14,Permanent lowland rivers,3.564844e+05,3.185748e+05,0.893657
15,Permanent salt and soda lakes,5.475716e+05,5.332370e+05,0.973821
16,"Polar/alpine cliffs, screes, outcrops and lava...",4.353077e+06,4.240441e+06,0.974125
17,Sandy Shorelines,9.638001e+02,8.484714e+02,0.880340
18,Seasonal floodplain marshes,2.049620e+05,1.812867e+05,0.884489
19,Seasonal freshwater lakes,4.332678e+02,4.332678e+02,1.000000
20,Seasonally dry temperate heath and shrublands,4.464365e+06,2.456261e+06,0.550193
21,Semi-desert steppe,9.208479e+06,9.059157e+06,0.983784
22,Small permanent freshwater lakes,6.159467e+04,6.108918e+04,0.991793
23,Succulent or Thorny deserts and semi-deserts,4.198207e+06,3.921328e+06,0.934048
24,Temperate alpine grasslands and shrublands,4.125732e+06,4.121051e+06,0.998865
25,Temperate subhumid grasslands,2.369767e+06,2.320867e+06,0.979365
26,Tropical alpine grasslands and herbfields,6.727136e+06,6.706926e+06,0.996996
27,Tropical/Subtropical dry forests and thickets,2.068678e+06,9.845929e+05,0.475953

In [6]:
print(f"Área Natural total: {efg_terrestre['area_natural'].sum():.2f} ha")

Área Natural total: 67590178.50 ha

### Flujo 2: Procesamiento Marino

#### Paso 2.1: Generación de la Capa Marina

Utilizar el polígono de la ZEE (200 millas).
Exclusión: Restar cualquier área que ya esté cubierta por el Catastro CONAF en la zona costera (ej. fiordos interiores o islas) para evitar doble contabilidad.

Ambos procesos se realizan en un script de python que elimina las intersecciones.

#### Paso 2.2: Intersección EFG Marino  (esperar capa EFG)

Cruzar el polígono de la ZEE con la capa de Grupos Funcionales Marinos de la UICN.
Esto clasificará el mar en grupos como M2 (Océano abierto pelágico), M3 (Mar profundo), etc.
> Nota: Se asume que toda la extensión de la ZEE es "Ecosistema Natural" a menos que existan capas específicas de "infraestructura marina artificial" (granjas eólicas, plataformas) que deban restarse (Clase M4/MT3). Ante la falta de datos de infraestructura marina, se contabiliza la ZEE total.

In [7]:
%%time
with engine.connect() as conn:
    efg_marino = pd.read_sql_query("""
        SELECT em."group", em.superf_ha "area_total", em.superf_ha "area_natural", em.superf_ha / em.superf_ha "porcentaje"
        FROM processed.efg_marino em;
    """, conn)
efg_marino

CPU times: user 3.13 ms, sys: 1.86 ms, total: 4.98 ms
Wall time: 199 ms

                                group    area_total  area_natural  porcentaje
0                      Abyssal plains  2.923908e+08  2.923908e+08         1.0
1   Coastal shrublands and grasslands  1.890645e+05  1.890645e+05         1.0
2       Continental and island slopes  5.634470e+07  5.634470e+07         1.0
3            Deepwater coastal inlets  7.370096e+06  7.370096e+06         1.0
4          Hadal trenches and troughs  3.877248e+06  3.877248e+06         1.0
5                        Kelp forests  1.201602e+07  1.201602e+07         1.0
6                    Rocky Shorelines  2.587972e+05  2.587972e+05         1.0
7                    Sandy Shorelines  4.507395e+05  4.507395e+05         1.0
8      Seamounts, ridges and plateaus  1.685113e+07  1.685113e+07         1.0
9                Subtidal rocky reefs  6.509729e+05  6.509729e+05         1.0
10                 Subtidal sand beds  2.826118e+06  2.826118e+06         1.0
11                    Upwelling zones  3.794770e+05  3.794770e+05         1.0

In [8]:
efg_marino_total = efg_marino["area_natural"].sum()
print(f"Área natural marino: {efg_marino_total:.2f} ha")

Área natural marino: 393605147.88 ha

## Paso 3: Integración y Cálculo

Unificar los resultados del Flujo 1 y Flujo 2.
Superficie Natural Total = (Sup. Natural CONAF) + (Sup. ZEE Natural).
Superficie Total País = Sup. Terrestre Oficial + Sup. ZEE Oficial.
Calcular proporción de áreas naturales en el territorio nacional

In [9]:
area_natural_total = area_natural + efg_marino_total
print(f"Área natural total (terrestre + marino): {area_natural_total:.2f} ha")

Área natural total (terrestre + marino): 460813579.17 ha